version: 2.1
orbs:
   node: circleci/node@3.0.0
   aws-cli: circleci/aws-cli@1.0
   serverless: circleci/serverless-framework@1.0
   serverless-bundle: serverless-bundle@4.1.0
   serverless-pseudo-parameters: serverless-pseudo-parameters@2.5.0
jobs:
   one:
     executor: serverless/default
     steps:
       - checkout
       - aws-cli/setup
       - serverless/setup
       - run: sls deploy 
workflows:
  one_and_two:
    jobs:
      - one