LibraryTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: LibraryTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    